---
baseURL: https://
title: 
# content
languageCode: en-us
enableRobotsTXT: true
publishdir: dist
metaDataFormat: yaml
disableKinds: ["taxonomyTerm"]
footnoteReturnLinkContents: â†©
summarylength: 40
enableEmoji: true
canonifyURLs: true
ignoreErrors: ["error-remote-getjson"]
timeout: "300s"

security:
  enableInlineShortcodes: false
  exec:
    allow: ["^dart-sass-embedded$", "^go$", "^npx$", "^postcss$", "^babel$"]

markup:
  highlight:
    codeFences: true
    guessSyntax: false
    style: dracula
    tabWidth: 2

mediaTypes:
  application/feed+json:
    suffixes:
      - json
  text/typescript:
    suffixes:
      - ts

outputFormats:
  jsonfeed:
    baseName: "feed"
    isPlainText: true
    mediaType: "application/feed+json"
  manifest:
    baseName: "manifest"
    isPlainText: true
    mediaType: application/feed+json
    name: "manifest"
    suffix: "json"
  social:
    baseName: "social"
    isPlainText: true
    mediaType: image/svg+xml
    name: "social"
    suffix: "svg"

taxonomies:
  tags: "tags"

permalinks:
  section: "/:filename/"
  blog: "/blog/:filename/"
  tags: "/tags/:slug/"

outputs:
  home: ["html", "manifest"]
  page: ["html", "social"]
  section: ["html", "jsonfeed", "rss", "social"]

sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5

params:
  meta:
    description: 
    author: 
    social: 
    background: "#1a1a1a"
    theme: "#c390f3"
